# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Tangram
version:      1.54_01
version_from: lib/Class/Tangram.pm
installdirs:  site
requires:
    Date::Manip:                   5.21
    Set::Object:                   1.04
    Test::Simple:                  0.18

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
